# This file was generated by GoReleaser. DO NOT EDIT.
cask "hippo" do
  version "0.1.0-alpha.11"

  on_macos do
    on_intel do
      sha256 "2188f91863b67cf60cfd9f376db175ed9bc0fe13cd4e5043a5d97e66d782c3b8"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
    on_arm do
      sha256 "8303e88140360fba4d04e9534436629d284d747400ed453a5ea2d10f57f6f9ca"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b2b10e8d8cc7518884bf074f4a99345e6f83623c6da913df200501b6d6ef27cc"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
    on_arm do
      sha256 "7474c8fe0b0cc7001347f8ef0e2f13bd6e6445b778da45ca6624cc1b6789375e"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
  end

  name "hippo"
  desc "Self-hosted AI memory system for local coding agents and humans."
  homepage "https://github.com/Forja-Labs-Mx/hippo-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hippo"

  # No zap stanza required

end
