# This file was generated by GoReleaser. DO NOT EDIT.
cask "hippo" do
  version "0.1.0-alpha.8"

  on_macos do
    on_intel do
      sha256 "31cd88864e686e4c116a01f1808f53291fae88551a2f0906c745fca162661301"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
    on_arm do
      sha256 "e05aef2bff5c9bf79381d8d08a2ab86f263bfbd735b9e1814fdc197877906cfc"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "9666744427eb83e16fa8aad3938f6631b375e3de5b4b21005a1e34741acb1511"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
    on_arm do
      sha256 "4b5a59c7d4b64d085d4b06404e7a3034ede2f70de5256f38a31a1a9bce0a5f2e"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
  end

  name "hippo"
  desc "Self-hosted AI memory system for local coding agents and humans."
  homepage "https://github.com/Forja-Labs-Mx/hippo-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hippo"

  # No zap stanza required

end
