# This file was generated by GoReleaser. DO NOT EDIT.
cask "hippo" do
  version "0.1.0-alpha.10"

  on_macos do
    on_intel do
      sha256 "f8b03c893a416d804b1082c23e5c906e3721aa6f2cb1538f8038951c62e585da"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
    on_arm do
      sha256 "00866587dd4d06795de7fa7c367d95de082d9765ad71d08b80d549b154f115a5"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e5e762eef7f40891c6666ce4798e122ca6e524123a735fd8ec850038890c745"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
    on_arm do
      sha256 "3151cce0d0d845ec1874122a9fb644aec75530311f470ae160970a42aadf12d6"
      url "https://github.com/Forja-Labs-Mx/hippo-releases/releases/download/v#{version}/hippo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Forja-Labs-Mx/hippo-releases/"
    end
  end

  name "hippo"
  desc "Self-hosted AI memory system for local coding agents and humans."
  homepage "https://github.com/Forja-Labs-Mx/hippo-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hippo"

  # No zap stanza required

end
